# (c) 2017 DataNexus Inc.  All Rights Reserved
---
- include_role:
    name: get-java-home
- include: add-spark-user.yml static=no
- include: install-apache-spark.yml static=no
- include_role:
    name: configure-spark-nodes
- include: create-spark-service.yml static=no
- include: start-spark-services.yml static=no
