# (c) 2017 DataNexus Inc.  All Rights Reserved
---
# enable ACLS and set the list of users/administrators that have view and
# modify access to all Spark jobs
- block:
  - name: Enable ACLS in the cluster
    lineinfile:
      dest: "{{spark_dir}}/conf/spark-defaults.conf"
      line: "spark.acls.enable:           true"
      insertafter: EOF
  - name: Set list of users/admins with view/modify access to all jobs
    lineinfile:
      dest: "{{spark_dir}}/conf/spark-defaults.conf"
      line: "spark.admin.acls:            {{spark_admin_list}}"
      insertafter: EOF
  become: true
  become_user: spark