# (c) 2017 DataNexus Inc.  All Rights Reserved
---
# setup secret to encrypt internode communication
- set_fact:
    shared_secret: 
- block:
  - name: Enable ACLS in the cluster
    lineinfile:
      dest: "{{spark_dir}}/conf/spark-defaults.conf"
      line: "{{item}}"
      insertafter: EOF
    with_items:
      - "spark.authenticate:          true"
      - "spark.authenticate.secret:   {{spark_cluster_secret}}"
  become: true
  become_user: spark
