# (c) 2016 DataNexus Inc.  All Rights Reserved
---
- set_fact:
    api_addr: "{{api_addr.split('\n').0}}"
- block:
  # setup sysctl to allow nginx to bind to non-local (virtual) address
  - name: Configure sysctl to allow non-local binding
    sysctl:
      name: "net.ipv4.ip_nonlocal_bind"
      value: 1
      state: present
  # first, make sure that the `keepalived` package is installed locally
  # since we'll be using that to control a set of nginx nodes that are
  # configured for an active-passive failover scenario
  - name: Install keepalived and dependencies
    package:
      name: "{{item}}"
      state: present
    with_items:
      - gcc
      - kernel-headers
      - kernel-devel
      - keepalived
  # use a Jinja2 template setup the initial keepalived configuration
  - name: Use template to setup new keepalived configuration
    template:
      src: keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf
      mode: 0644
  # add a `unicast_peer` definition to the configuration file
  - name: Modify the new configuration to include the other cluster members
    lineinfile:
      dest: /etc/keepalived/keepalived.conf
      line: "    unicast_peer {\n    }"
      insertafter: "unicast_src_ip"
      state: present
  - lineinfile:
      dest: /etc/keepalived/keepalived.conf
      line: "        {{item}}"
      insertafter: "unicast_peer"
      state: present
    with_items: "{{spark_master_bind_ips | difference([bind_address]) | reverse | list}}"
  # setup the local machine to forward any requests received on the virtual IP
  # address to the IP address that the WebUI is listening on using iptables
  - name: Make sure iptables-services package is installed
    package:
      name: iptables-services
      state: present
  - name: Enable iptables service at boot
    service:
      name: iptables
      enabled: yes
  - name: Configure port forwarding with iptables
    shell: "{{item}}"
    with_items:
      - "sysctl net.ipv4.ip_forward=1"
      - "iptables -t nat -A PREROUTING -p tcp -d {{spark_master_virtual_ip}} --dport {{spark_master_webui_port}} -j DNAT --to {{bind_address}}:{{spark_master_webui_port}}"
      - "iptables -A FORWARD -p tcp -d {{bind_address}} --dport {{spark_master_webui_port}} -j ACCEPT"
      - "iptables-save > /etc/sysconfig/iptables"
  - name: Restart iptables service to pickup changes
    service:
      name: iptables
      state: restarted
  become: true
