# (c) 2017 DataNexus Inc.  All Rights Reserved
---
# ensure that the service file for each node in the cluster is up to date
# (if we're moving from an insecure to secure cluster we need to change from
# services listening on the `api_iface` to services listening on the
# `data_iface`, so the service file needs to be updated)
- block:
  - name: Create spark service file
    template:
      src: "spark-{{cluster_role | default('worker')}}.service.j2"
      dest: "/etc/systemd/system/spark-{{cluster_role | default('worker')}}.service"
      mode: 0644
  - name: restart systemctl daemon
    command: systemctl daemon-reload
  become: true