# (c) 2017 DataNexus Inc.  All Rights Reserved
---
# first ensure that, if the `reverse_proxy_url` parameter is defined, the
# Spark nodes are configured so that traffic destined for the cluster can
# be forwarded through the defined proxy
- block:
  - name: Test for existence of reverse proxy URL
    fail: msg="Reverse Proxy not defined"
    when: reverse_proxy_url | default('') == ''
- name: configure master nodes to reverseProxy connections for the workers
  lineinfile:
    dest: "{{spark_dir}}/conf/spark-defaults.conf"
    line: "spark.ui.reverseProxyUrl:    {{reverse_proxy_url}}"
    insertafter: EOF
  become: true
  become_user: spark
# then add the `/spark` endpoint to each of our nginx instances and configure
# that endoint to act as a reverse proxy for the Spark cluster
- block:
  - name: Add '/spark' endpoint to NGINX instances
    include: add-spark-endpoint.yml static=no
    delegate_to: "{{nginx_host}}"
    run_once: true
    with_items: "{{nginx_nodes}}"
    loop_control:
      loop_var: nginx_host
  become: true
